type assetsInfoProps = {
    title: string,
    shortTitle: string,
    description: string,
    siteIcon: string,
    twitterImage: string,
    cardImage: string,
    bannerImage: string,
    googleMap: string,
    whatsapp1: string,
    whatsapp2: string,
    instagram: string,
    facebook: string,
    email: string,
    site: string,
}
export const assetsInfo: assetsInfoProps = {
    title: "Dynamix Fitness Center",
    shortTitle: "Dynamix Fitness",
    description: "Our Dynamix Fitness Centre gym is our largest club, and our first dual-concept Dynamix location.",
    siteIcon: "/images/pic3.jpg",
    twitterImage: "https://i.ibb.co/K7tXKg1/icon.jpg",
    cardImage: "/images/pic3.jpg",
    bannerImage: "/images/banner.jpg",
    googleMap: process.env.NEXT_PUBLIC_GOOGLEMAP_URL as string,
    whatsapp1: process.env.NEXT_PUBLIC_WHATSAPP1 as string,
    whatsapp2: process.env.NEXT_PUBLIC_WHATSAPP2 as string,
    instagram: process.env.NEXT_PUBLIC_INSTAGRAM as string,
    facebook: process.env.NEXT_PUBLIC_FACEBOOK as string,
    email: process.env.NEXT_PUBLIC_EMAIL as string,
    site: "https://dynamix-gym.pages.dev",
}
